### ISSUE TITLE
Socialite error

### ISSUE THREAD

**Issue by quasiperfect** [apiato/apiato#123]
hi
i tried to use social auth and i get the error
```
{"message":"Target [Laravel\\Socialite\\Contracts\\Factory] is not instantiable.","status_code":500,"debug":{"line":873,"file":"D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php","class":"Illuminate\\Contracts\\Container\\BindingResolutionException","trace":["#0 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(725): Illuminate\\Container\\Container->notInstantiable('Laravel\\\\Sociali...')","#1 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(598): Illuminate\\Container\\Container->build('Laravel\\\\Sociali...')","#2 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(567): Illuminate\\Container\\Container->resolve('Laravel\\\\Sociali...')","#3 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(702): Illuminate\\Container\\Container->make('Laravel\\\\Sociali...')","#4 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(1139): Illuminate\\Foundation\\Application->make('Laravel\\\\Sociali...')","#5 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(159): Illuminate\\Container\\Container->offsetGet('Laravel\\\\Sociali...')","#6 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(128): Illuminate\\Support\\Facades\\Facade::resolveFacadeInstance('Laravel\\\\Sociali...')","#7 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(215): Illuminate\\Support\\Facades\\Facade::getFacadeRoot()","#8 D:\\laragon\\www\\apiato\\app\\Containers\\Socialauth\\UI\\WEB\\Controllers\\Controller.php(23): Illuminate\\Support\\Facades\\Facade::__callStatic('driver', Array)","#9 [internal function]: App\\Containers\\SocialAuth\\UI\\WEB\\Controllers\\Controller->redirectAll('facebook')","#10 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(55): call_user_func_array(Array, Array)","#11 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(44): Illuminate\\Routing\\Controller->callAction('redirectAll', Array)","#12 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(203): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Containers\\SocialAuth\\UI\\WEB\\Controllers\\Controller), 'redirectAll')","#13 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(160): Illuminate\\Routing\\Route->runController()","#14 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(559): Illuminate\\Routing\\Route->run()","#15 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))","#16 D:\\laragon\\www\\apiato\\app\\Containers\\Localization\\Middlewares\\LocalizationMiddleware.php(34): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))","#17 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(148): App\\Containers\\Localization\\Middlewares\\LocalizationMiddleware->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#18 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#19 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))","#20 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(148): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#21 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#22 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php(65): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))","#23 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(148): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#24 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#25 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))","#26 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(148): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#27 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#28 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(64): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))","#29 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(148): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#30 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#31 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))","#32 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(148): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#33 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#34 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php(59): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))","#35 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(148): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#36 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#37 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))","#38 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(561): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))","#39 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(520): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Dingo\\Api\\Http\\Request))","#40 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(498): Illuminate\\Routing\\Router->dispatchToRoute(Object(Dingo\\Api\\Http\\Request))","#41 D:\\laragon\\www\\apiato\\vendor\\dingo\\api\\src\\Routing\\Adapter\\Laravel.php(81): Illuminate\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))","#42 D:\\laragon\\www\\apiato\\vendor\\dingo\\api\\src\\Routing\\Router.php(513): Dingo\\Api\\Routing\\Adapter\\Laravel->dispatch(Object(Dingo\\Api\\Http\\Request), 'v1')","#43 D:\\laragon\\www\\apiato\\vendor\\dingo\\api\\src\\Http\\Middleware\\Request.php(126): Dingo\\Api\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))","#44 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(114): Dingo\\Api\\Http\\Middleware\\Request->Dingo\\Api\\Http\\Middleware\\{closure}(Object(Dingo\\Api\\Http\\Request))","#45 D:\\laragon\\www\\apiato\\vendor\\barryvdh\\laravel-cors\\src\\HandleCors.php(34): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#46 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(148): Barryvdh\\Cors\\HandleCors->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#47 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#48 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(148): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#49 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#50 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(148): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#51 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#52 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(148): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#53 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(46): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#54 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(148): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#55 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(102): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#56 D:\\laragon\\www\\apiato\\vendor\\dingo\\api\\src\\Http\\Middleware\\Request.php(127): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))","#57 D:\\laragon\\www\\apiato\\vendor\\dingo\\api\\src\\Http\\Middleware\\Request.php(103): Dingo\\Api\\Http\\Middleware\\Request->sendRequestThroughRouter(Object(Dingo\\Api\\Http\\Request))","#58 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(148): Dingo\\Api\\Http\\Middleware\\Request->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#59 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))","#60 D:\\laragon\\www\\apiato\\app\\Containers\\Debugger\\Middlewares\\RequestsMonitorMiddleware.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))","#61 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(148): App\\Containers\\Debugger\\Middlewares\\RequestsMonitorMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))","#62 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))","#63 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))","#64 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(149): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))","#65 D:\\laragon\\www\\apiato\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))","#66 D:\\laragon\\www\\apiato\\public\\index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))","#67 {main}"]}}
```

**Comment by Mahmoudz** [comment]
@quasiperfect haven't touched this feature for a long time, and I remember it's unit test is weak! so if solved please share it. I imagine it needs some refactoring as well, as I extracted this feature from an old project.

**Comment by erayaydin** [comment]
Still bug happen

```
local.ERROR: Target [Laravel\Socialite\Contracts\Factory] is not instantiable.
```
