### ISSUE TITLE
Blank screen on documentation

### ISSUE THREAD

**Issue by mylonick** [apiato/apiato#289]
**I get a blank screen instead of a documentation page after successfully** 

`php artisan apiato:docs`

**as i get** 

```
`Generating API Documentations for (public & private)

[public] apidoc -c app/Containers/Documentation/ApiDocJs/public -f public.php -i app -o public/api/documentation
Result: info: Done.

[private] apidoc -c app/Containers/Documentation/ApiDocJs/private -f private.php -f public.php -i app -o public/api/private/documentation
Result: info: Done.

Done! You can access your API Docs at: 
> http://******.com/api/documentation
> http://******.com/api/private/documentation`

```

**Please note that i run the command as root, as when i run it as the user i get**

```
> `Generating API Documentations for (public & private)
> 
> [public] apidoc -c app/Containers/Documentation/ApiDocJs/public -f public.php -i app -o public/api/documentation
> Result: warn:  Error: EACCES: permission denied, scandir '/home'
>     at Object.fs.readdirSync (fs.js:906:18)
>     at GlobSync._readdir (/usr/local/lib/node_modules/apidoc/node_modules/glob/sync.js:288:41)
>     at GlobSync._processReaddir (/usr/local/lib/node_modules/apidoc/node_modules/glob/sync.js:137:22)
>     at GlobSync._process (/usr/local/lib/node_modules/apidoc/node_modules/glob/sync.js:132:10)
>     at new GlobSync (/usr/local/lib/node_modules/apidoc/node_modules/glob/sync.js:48:10)
>     at Function.globSync [as sync] (/usr/local/lib/node_modules/apidoc/node_modules/glob/sync.js:26:10)
>     at PluginLoader.detectPugins (/usr/local/lib/node_modules/apidoc/node_modules/apidoc-core/lib/plugin_loader.js:49:20)
>     at PluginLoader.detectPugins (/usr/local/lib/node_modules/apidoc/node_modules/apidoc-core/lib/plugin_loader.js:61:17)
>     at PluginLoader.detectPugins (/usr/local/lib/node_modules/apidoc/node_modules/apidoc-core/lib/plugin_loader.js:61:17)
>     at PluginLoader.detectPugins (/usr/local/lib/node_modules/apidoc/node_modules/apidoc-core/lib/plugin_loader.js:61:17)
> info: Done.
> 
> [private] apidoc -c app/Containers/Documentation/ApiDocJs/private -f private.php -f public.php -i app -o public/api/private/documentation
> Result: warn:  Error: EACCES: permission denied, scandir '/home'
>     at Object.fs.readdirSync (fs.js:906:18)
>     at GlobSync._readdir (/usr/local/lib/node_modules/apidoc/node_modules/glob/sync.js:288:41)
>     at GlobSync._processReaddir (/usr/local/lib/node_modules/apidoc/node_modules/glob/sync.js:137:22)
>     at GlobSync._process (/usr/local/lib/node_modules/apidoc/node_modules/glob/sync.js:132:10)
>     at new GlobSync (/usr/local/lib/node_modules/apidoc/node_modules/glob/sync.js:48:10)
>     at Function.globSync [as sync] (/usr/local/lib/node_modules/apidoc/node_modules/glob/sync.js:26:10)
>     at PluginLoader.detectPugins (/usr/local/lib/node_modules/apidoc/node_modules/apidoc-core/lib/plugin_loader.js:49:20)
>     at PluginLoader.detectPugins (/usr/local/lib/node_modules/apidoc/node_modules/apidoc-core/lib/plugin_loader.js:61:17)
>     at PluginLoader.detectPugins (/usr/local/lib/node_modules/apidoc/node_modules/apidoc-core/lib/plugin_loader.js:61:17)
>     at PluginLoader.detectPugins (/usr/local/lib/node_modules/apidoc/node_modules/apidoc-core/lib/plugin_loader.js:61:17)
> info: Done.
> 
> Done! You can access your API Docs at: 
> > http://******.com/api/documentation
> > http://******.com/api/private/documentation`
> 
```

**Comment by johannesschobel** [comment]
I am not sure about this error.. But in your error log it reads:
> Result: Warn: Error: EACCES: permission denied, scandir /home

Maybe this causes the error?

**Comment by mylonick** [comment]
@johannesschobel 
**I don't think this is the problem, since everything goes well when i  execute as root**

root@******* [/home/newpi/public_html]# php artisan apiato:docs
Generating API Documentations for (public & private)

[public] apidoc -c app/Containers/Documentation/ApiDocJs/public -f public.php -i app -o public/api/documentation
Result: info: Done.

[private] apidoc -c app/Containers/Documentation/ApiDocJs/private -f private.php -f public.php -i app -o public/api/private/documentation
Result: info: Done.

Done! You can access your API Docs at: 
> http://*******.gr/api/documentation
> http://*******.gr/api/private/documentation

**Comment by mylonick** [comment]
Seems to be working in the link 
http://mydomain.com/public/api/private/documentation/

So, it needs [public] in the url, even though i've done the settings to remove public from the url.

**Comment by johannesschobel** [comment]
yes, but still - as root you have full access to the path.. if you execute the script as a normal user, you might not have the "write / execute access" on this directory. Can you try to change the permissions for this user on this directory?

Furthermore - is this issue resolved?

**Comment by mylonick** [comment]
Partially yes, even though it was supposed to work without 'public' on the url, right ?
