### ISSUE TITLE
VendorSection needs to be replace with Vendor 

### ISSUE THREAD

**Issue by ikkysleepy** [apiato/apiato#629]
### Description:
```
  Class 'App\Containers\VendorSection\Debugger\Providers\MainServiceProvider' not found
```

```
[2021-04-28 21:44:14] local.ERROR: Class 'App\Containers\VendorSection\Debugger\Providers\MainServiceProvider' not found {"exception":"[object] (Error(code: 0): Class 'App\\Containers\\VendorSection\\Debugger\\Providers\\MainServiceProvider' not found at /home/vagrant/code/koritsu-www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:735)
[stacktrace]
#0 /home/vagrant/code/koritsu-www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(669): Illuminate\\Foundation\\Application->resolveProvider()
#1 /home/vagrant/code/koritsu-www/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Foundation\\Application->register()
#2 /home/vagrant/code/koritsu-www/vendor/apiato/core/Loaders/ProvidersLoaderTrait.php(46): Illuminate\\Support\\Facades\\Facade::__callStatic()
#3 /home/vagrant/code/koritsu-www/vendor/apiato/core/Loaders/ProvidersLoaderTrait.php(37): Apiato\\Core\\Providers\\ApiatoProvider->loadProvider()
#4 /home/vagrant/code/koritsu-www/vendor/apiato/core/Loaders/ProvidersLoaderTrait.php(22): Apiato\\Core\\Providers\\ApiatoProvider->loadProviders()
#5 /home/vagrant/code/koritsu-www/vendor/apiato/core/Loaders/AutoLoaderTrait.php(37): Apiato\\Core\\Providers\\ApiatoProvider->loadOnlyMainProvidersFromContainers()
#6 /home/vagrant/code/koritsu-www/vendor/apiato/core/Providers/ApiatoProvider.php(23): Apiato\\Core\\Providers\\ApiatoProvider->runLoadersBoot()
#7 /home/vagrant/code/koritsu-www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Apiato\\Core\\Providers\\ApiatoProvider->boot()
#8 /home/vagrant/code/koritsu-www/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#9 /home/vagrant/code/koritsu-www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#10 /home/vagrant/code/koritsu-www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#11 /home/vagrant/code/koritsu-www/vendor/laravel/framework/src/Illuminate/Container/Container.php(611): Illuminate\\Container\\BoundMethod::call()
#12 /home/vagrant/code/koritsu-www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(914): Illuminate\\Container\\Container->call()
#13 /home/vagrant/code/koritsu-www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(895): Illuminate\\Foundation\\Application->bootProvider()
#14 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}()
#15 /home/vagrant/code/koritsu-www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(896): array_walk()
#16 /home/vagrant/code/koritsu-www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#17 /home/vagrant/code/koritsu-www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap()
#18 /home/vagrant/code/koritsu-www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\\Foundation\\Application->bootstrapWith()
#19 /home/vagrant/code/koritsu-www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(127): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#20 /home/vagrant/code/koritsu-www/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#21 {main}
"} 
```

### Additional Context:
Update MiddleServiceProvider and MainServiceProvider

Actually "VendorSection" exists in dozen of files, just do a simple replace for the entire project.
```
find ./ -type f -exec sed -i 's/VendorSection/Vendor/g' {} \;
```

Also don't forget about vendorSection
```
find ./ -type f -exec sed -i 's/vendorSection/vendor/g' {} \;
```

### Versions:
- Apiato Version: 10.0 (lastest)
- PHP Version: 7.4

### Steps To Reproduce:
1. Composer Install fails

**Comment by Mohammad-Alavi** [comment]
I couldn't replicate this issue. If you have encountered it again or find a consistent way to reproduce it reopen this or report it in another issue.
