### ISSUE TITLE
PHP 7.4 error installing Apiato

### ISSUE THREAD

**Issue by ikkysleepy** [apiato/apiato#643]
### Description:
```
composer/package-versions-deprecated: ...done generating version class
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
PHP Fatal error:  During class fetch: Uncaught ParseError: syntax error, unexpected '|', expecting variable (T_VARIABLE) in /Users/jorge/code/milo_www/vendor/apiato/core/Traits/HasRequestCriteriaTrait.php:73
Stack trace:
#0 /Users/jorge/code/milo_www/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile('/Users/jorge/co...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Apiato\\Core\\Tra...')
#2 /Users/jorge/code/milo_www/vendor/apiato/core/Abstracts/Tasks/Task.php(7): spl_autoload_call('Apiato\\Core\\Tra...')
#3 /Users/jorge/code/milo_www/vendor/composer/ClassLoader.php(480): include('/Users/jorge/co...')
#4 /Users/jorge/code/milo_www/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile('/Users/jorge/co...')
#5 [internal function]: Composer\Autoload\ClassLoader->loadClass('Apiato\\Core\\Abs...')
#6 /Users/jorge/code/milo_www/app/Ship/Parents/Tasks/Task.php(7): spl_autoload_call('Apiato\\Core\\Abs...')
#7 /Users/jorge/code/milo_www/vendor/composer/ClassLoader.php(480): include(' in /Users/jorge/code/milo_www/vendor/apiato/core/Abstracts/Tasks/Task.php on line 7

In Task.php line 7:

  During class fetch: Uncaught ParseError: syntax error, unexpected '|', expecting variable (T_VARIABLE) in /Users/jorge/code/m
  ilo_www/vendor/apiato/core/Traits/HasRequestCriteriaTrait.php:73
  Stack trace:
  #0 /Users/jorge/code/milo_www/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile('/Users/jorge/co...')
  #1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Apiato\\Core\\Tra...')
  #2 /Users/jorge/code/milo_www/vendor/apiato/core/Abstracts/Tasks/Task.php(7): spl_autoload_call('Apiato\\Core\\Tra...')
  #3 /Users/jorge/code/milo_www/vendor/composer/ClassLoader.php(480): include('/Users/jorge/co...')
  #4 /Users/jorge/code/milo_www/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile('/Users/jorge/co...')
  #5 [internal function]: Composer\Autoload\ClassLoader->loadClass('Apiato\\Core\\Abs...')
  #6 /Users/jorge/code/milo_www/app/Ship/Parents/Tasks/Task.php(7): spl_autoload_call('Apiato\\Core\\Abs...')
  #7 /Users/jorge/code/milo_www/vendor/composer/ClassLoader.php(480): include('


Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 255

Apiato ready! Build something amazing.
```
### Expected Behavior:
No errors

### Additional Context:
I tried two methods of installing a new repo, both failed on php 7.4. error doesn't look like it appears in php 8

### Versions:
- Apiato Version: Latest
- PHP Version: 7.4

### Steps To Reproduce:
1. Run the command ```composer create-project apiato/apiato my-api```

**Comment by Ezkahan** [comment]
update your HasRequestCriteriaTrait.php
location: vendor/apiato/core/Traits/HasRequestCriteriaTrait.php

Replace:
private function isSearching(array|string|null $query): bool

To:
private function isSearching(array $query): bool


and  run  composer install
