### ISSUE TITLE
Custom Model primaryKey not working!

### ISSUE THREAD

**Issue by davidreyg** [apiato/apiato#728]
### Apiato Version

12.0.0

### PHP Version

8.2

### Database Driver & Version

Mysql in Linux Mint

### Description

I have a model Person  with a hasOne realtionship with User.
But my User model does not have its own primary key. Instead its using person_id (PFK) as primary key.

```
class Person extends ParentModel
{
    protected $fillable = [
        'names',
        'surnames',
        'email',
        'gender',
        'religion',
        'birth',
        'phone',
        'university_code',
    ];

    protected $casts = [
        'phone'           => 'integer',
        'university_code' => 'integer',
        'birth'           => 'date',
    ];

    /**
     * A resource key to be used in the serialized responses.
     */
    protected string $resourceKey = 'Person';

    public function user()
    {
        return $this->hasOne(User::class, 'person_id');
    }
}
```
```
class User extends ParentUserModel implements MustVerifyEmail
{
    use AuthorizationTrait;
    use AuthenticationTrait;

    protected $primaryKey = 'person_id';
    public $incrementing = false;
    protected $fillable = [
        'name',
        'email',
        'password',
        'person_id',
    ];
    //...more stuff
}

```

### Steps To Reproduce

Define a UserFactory and run  GetAllUsersTest@testSearchUsersByHashID

```
class UserFactory extends ParentFactory
{
    protected $model = User::class;

    public function definition(): array
    {
        static $password;

        return [
            'person_id' => Person::factory()->create()->id,
            'name'      => $this->faker->name(),
            'email'     => $this->faker->unique()->safeEmail(),
            'password'  => $password ?: $password = Hash::make('testing-password'),
            // 'email_verified_at' => now(),
            // 'remember_token' => Str::random(10),
            // 'gender' => $this->faker->randomElement(['male', 'female', 'unspecified']),
            // 'birth' => $this->faker->date(),
        ];
    }
}

```
```
/**
 * @group user
 * @group api
 */
class GetAllUsersTest extends ApiTestCase
{
    protected string $endpoint = 'get@v1/users';

    protected array $access = [
        'permissions' => 'list-users',
        'roles'       => '',
    ];

    public function testSearchUsersByHashID(): void
    {
       User::factory()->count(3)->create();
        $user = $this->getTestingUser();

        $response = $this->endpoint($this->endpoint . '?search=id:' . $user->getHashedKey())->makeCall();

        $response->assertOk();
        $response->assertJson(
            fn(AssertableJson $json) => $json->has('data')
                ->where('data.0.id', $user->getHashedKey())
                ->etc()
        );
    }
}

```

Seems to somehow its still looking for 'id' field. 

**ERROR :/**
```

Expected response status code [200] but received 500.
Failed asserting that 200 is identical to 500.

The following exception occurred during the last request:

PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.id' in 'where clause' in /var/www/apiato/vendor/laravel/framework/src/Illuminate/Database/Connection.php:416
Stack trace:
#0 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Database/Connection.php(416): PDO->prepare()
#1 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Database/Connection.php(809): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#2 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Database/Connection.php(776): Illuminate\Database\Connection->runQueryCallback()
#3 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Database/Connection.php(407): Illuminate\Database\Connection->run()
#4 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2751): Illuminate\Database\Connection->select()
#5 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2740): Illuminate\Database\Query\Builder->runSelect()
#6 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3294): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#7 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2739): Illuminate\Database\Query\Builder->onceWithColumns()
#8 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2904): Illuminate\Database\Query\Builder->get()
#9 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2863): Illuminate\Database\Query\Builder->runPaginationCountQuery()
#10 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(921): Illuminate\Database\Query\Builder->getCountForPagination()
#11 /var/www/apiato/vendor/prettus/l5-repository/src/Prettus/Repository/Eloquent/BaseRepository.php(487): Illuminate\Database\Eloquent\Builder->paginate()
#12 /var/www/apiato/vendor/prettus/l5-repository/src/Prettus/Repository/Traits/CacheableRepository.php(238): Prettus\Repository\Eloquent\BaseRepository->paginate()
#13 /var/www/apiato/vendor/apiato/core/Abstracts/Repositories/Repository.php(102): Apiato\Core\Abstracts\Repositories\Repository->cacheablePaginate()
#14 /var/www/apiato/app/Containers/AppSection/User/Tasks/GetAllUsersTask.php(23): Apiato\Core\Abstracts\Repositories\Repository->paginate()
#15 /var/www/apiato/app/Containers/AppSection/User/Actions/GetAllUsersAction.php(23): App\Containers\AppSection\User\Tasks\GetAllUsersTask->run()
#16 /var/www/apiato/app/Containers/AppSection/User/UI/API/Controllers/GetAllUsersController.php(19): App\Containers\AppSection\User\Actions\GetAllUsersAction->run()
#17 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Containers\AppSection\User\UI\API\Controllers\GetAllUsersController->__invoke()
#18 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\Routing\Controller->callAction()
#19 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\Routing\ControllerDispatcher->dispatch()
#20 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route->runController()
#21 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\Routing\Route->run()
#22 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#23 /var/www/apiato/vendor/apiato/core/Middlewares/Http/ProfilerMiddleware.php(14): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#24 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Apiato\Core\Middlewares\Http\ProfilerMiddleware->handle()
#25 /var/www/apiato/vendor/apiato/core/Middlewares/Http/ProcessETagHeadersMiddleware.php(24): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#26 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Apiato\Core\Middlewares\Http\ProcessETagHeadersMiddleware->handle()
#27 /var/www/apiato/vendor/apiato/core/Middlewares/Http/ValidateJsonContent.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#28 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Apiato\Core\Middlewares\Http\ValidateJsonContent->handle()
#29 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#30 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings->handle()
#31 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(159): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#32 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(125): Illuminate\Routing\Middleware\ThrottleRequests->handleRequest()
#33 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(87): Illuminate\Routing\Middleware\ThrottleRequests->handleRequestUsingNamedLimiter()
#34 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\ThrottleRequests->handle()
#35 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#36 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Auth\Middleware\Authenticate->handle()
#37 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#38 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\Pipeline\Pipeline->then()
#39 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Routing/Router.php(777): Illuminate\Routing\Router->runRouteWithinStack()
#40 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Routing/Router.php(741): Illuminate\Routing\Router->runRoute()
#41 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Routing/Router.php(730): Illuminate\Routing\Router->dispatchToRoute()
#42 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\Routing\Router->dispatch()
#43 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#44 /var/www/apiato/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#45 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle()
#46 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#47 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#48 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#49 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#50 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#51 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\TrimStrings->handle()
#52 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#53 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
#54 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#55 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#56 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#57 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\HandleCors->handle()
#58 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#59 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\TrustProxies->handle()
#60 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#61 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\Pipeline\Pipeline->then()
#62 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#63 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php(573): Illuminate\Foundation\Http\Kernel->handle()
#64 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php(539): Illuminate\Foundation\Testing\TestCase->call()
#65 /var/www/apiato/vendor/apiato/core/Traits/TestTraits/PhpUnit/TestRequestHelperTrait.php(76): Illuminate\Foundation\Testing\TestCase->json()
#66 /var/www/apiato/app/Containers/AppSection/User/UI/API/Tests/Functional/GetAllUsersTest.php(73): Apiato\Core\Abstracts\Tests\PhpUnit\TestCase->makeCall()
#67 /var/www/apiato/vendor/phpunit/phpunit/src/Framework/TestCase.php(1114): App\Containers\AppSection\User\UI\API\Tests\Functional\GetAllUsersTest->testSearchUsersByHashID()
#68 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php(174): PHPUnit\Framework\TestCase->runTest()
#69 /var/www/apiato/vendor/phpunit/phpunit/src/Framework/TestCase.php(653): Illuminate\Foundation\Testing\TestCase->runTest()
#70 /var/www/apiato/vendor/phpunit/phpunit/src/Framework/TestRunner.php(103): PHPUnit\Framework\TestCase->runBare()
#71 /var/www/apiato/vendor/phpunit/phpunit/src/Framework/TestCase.php(489): PHPUnit\Framework\TestRunner->run()
#72 /var/www/apiato/vendor/phpunit/phpunit/src/Framework/TestSuite.php(340): PHPUnit\Framework\TestCase->run()
#73 /var/www/apiato/vendor/phpunit/phpunit/src/Framework/TestSuite.php(340): PHPUnit\Framework\TestSuite->run()
#74 /var/www/apiato/vendor/phpunit/phpunit/src/Framework/TestSuite.php(340): PHPUnit\Framework\TestSuite->run()
#75 /var/www/apiato/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(63): PHPUnit\Framework\TestSuite->run()
#76 /var/www/apiato/vendor/phpunit/phpunit/src/TextUI/Application.php(189): PHPUnit\TextUI\TestRunner->run()
#77 /var/www/apiato/vendor/phpunit/phpunit/phpunit(99): PHPUnit\TextUI\Application->run()
#78 /var/www/apiato/vendor/bin/phpunit(122): include('...')
#79 {main}

Next Illuminate\Database\QueryException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.id' in 'where clause' (Connection: mysql, SQL: select count(*) as aggregate from `users` where (`users`.`id` = 8)) in /var/www/apiato/vendor/laravel/framework/src/Illuminate/Database/Connection.php:822
Stack trace:
#0 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Database/Connection.php(776): Illuminate\Database\Connection->runQueryCallback()
#1 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Database/Connection.php(407): Illuminate\Database\Connection->run()
#2 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2751): Illuminate\Database\Connection->select()
#3 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2740): Illuminate\Database\Query\Builder->runSelect()
#4 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3294): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#5 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2739): Illuminate\Database\Query\Builder->onceWithColumns()
#6 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2904): Illuminate\Database\Query\Builder->get()
#7 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2863): Illuminate\Database\Query\Builder->runPaginationCountQuery()
#8 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(921): Illuminate\Database\Query\Builder->getCountForPagination()
#9 /var/www/apiato/vendor/prettus/l5-repository/src/Prettus/Repository/Eloquent/BaseRepository.php(487): Illuminate\Database\Eloquent\Builder->paginate()
#10 /var/www/apiato/vendor/prettus/l5-repository/src/Prettus/Repository/Traits/CacheableRepository.php(238): Prettus\Repository\Eloquent\BaseRepository->paginate()
#11 /var/www/apiato/vendor/apiato/core/Abstracts/Repositories/Repository.php(102): Apiato\Core\Abstracts\Repositories\Repository->cacheablePaginate()
#12 /var/www/apiato/app/Containers/AppSection/User/Tasks/GetAllUsersTask.php(23): Apiato\Core\Abstracts\Repositories\Repository->paginate()
#13 /var/www/apiato/app/Containers/AppSection/User/Actions/GetAllUsersAction.php(23): App\Containers\AppSection\User\Tasks\GetAllUsersTask->run()
#14 /var/www/apiato/app/Containers/AppSection/User/UI/API/Controllers/GetAllUsersController.php(19): App\Containers\AppSection\User\Actions\GetAllUsersAction->run()
#15 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Containers\AppSection\User\UI\API\Controllers\GetAllUsersController->__invoke()
#16 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\Routing\Controller->callAction()
#17 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\Routing\ControllerDispatcher->dispatch()
#18 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route->runController()
#19 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\Routing\Route->run()
#20 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#21 /var/www/apiato/vendor/apiato/core/Middlewares/Http/ProfilerMiddleware.php(14): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#22 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Apiato\Core\Middlewares\Http\ProfilerMiddleware->handle()
#23 /var/www/apiato/vendor/apiato/core/Middlewares/Http/ProcessETagHeadersMiddleware.php(24): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#24 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Apiato\Core\Middlewares\Http\ProcessETagHeadersMiddleware->handle()
#25 /var/www/apiato/vendor/apiato/core/Middlewares/Http/ValidateJsonContent.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#26 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Apiato\Core\Middlewares\Http\ValidateJsonContent->handle()
#27 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#28 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings->handle()
#29 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(159): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#30 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(125): Illuminate\Routing\Middleware\ThrottleRequests->handleRequest()
#31 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(87): Illuminate\Routing\Middleware\ThrottleRequests->handleRequestUsingNamedLimiter()
#32 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\ThrottleRequests->handle()
#33 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#34 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Auth\Middleware\Authenticate->handle()
#35 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#36 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\Pipeline\Pipeline->then()
#37 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Routing/Router.php(777): Illuminate\Routing\Router->runRouteWithinStack()
#38 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Routing/Router.php(741): Illuminate\Routing\Router->runRoute()
#39 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Routing/Router.php(730): Illuminate\Routing\Router->dispatchToRoute()
#40 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\Routing\Router->dispatch()
#41 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#42 /var/www/apiato/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#43 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle()
#44 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#45 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#46 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#47 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#48 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#49 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\TrimStrings->handle()
#50 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#51 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
#52 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#53 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#54 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#55 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\HandleCors->handle()
#56 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#57 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\TrustProxies->handle()
#58 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#59 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\Pipeline\Pipeline->then()
#60 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#61 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php(573): Illuminate\Foundation\Http\Kernel->handle()
#62 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php(539): Illuminate\Foundation\Testing\TestCase->call()
#63 /var/www/apiato/vendor/apiato/core/Traits/TestTraits/PhpUnit/TestRequestHelperTrait.php(76): Illuminate\Foundation\Testing\TestCase->json()
#64 /var/www/apiato/app/Containers/AppSection/User/UI/API/Tests/Functional/GetAllUsersTest.php(73): Apiato\Core\Abstracts\Tests\PhpUnit\TestCase->makeCall()
#65 /var/www/apiato/vendor/phpunit/phpunit/src/Framework/TestCase.php(1114): App\Containers\AppSection\User\UI\API\Tests\Functional\GetAllUsersTest->testSearchUsersByHashID()
#66 /var/www/apiato/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php(174): PHPUnit\Framework\TestCase->runTest()
#67 /var/www/apiato/vendor/phpunit/phpunit/src/Framework/TestCase.php(653): Illuminate\Foundation\Testing\TestCase->runTest()
#68 /var/www/apiato/vendor/phpunit/phpunit/src/Framework/TestRunner.php(103): PHPUnit\Framework\TestCase->runBare()
#69 /var/www/apiato/vendor/phpunit/phpunit/src/Framework/TestCase.php(489): PHPUnit\Framework\TestRunner->run()
#70 /var/www/apiato/vendor/phpunit/phpunit/src/Framework/TestSuite.php(340): PHPUnit\Framework\TestCase->run()
#71 /var/www/apiato/vendor/phpunit/phpunit/src/Framework/TestSuite.php(340): PHPUnit\Framework\TestSuite->run()
#72 /var/www/apiato/vendor/phpunit/phpunit/src/Framework/TestSuite.php(340): PHPUnit\Framework\TestSuite->run()
#73 /var/www/apiato/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(63): PHPUnit\Framework\TestSuite->run()
#74 /var/www/apiato/vendor/phpunit/phpunit/src/TextUI/Application.php(189): PHPUnit\TextUI\TestRunner->run()
#75 /var/www/apiato/vendor/phpunit/phpunit/phpunit(99): PHPUnit\TextUI\Application->run()
#76 /var/www/apiato/vendor/bin/phpunit(122): include('...')
#77 {main}

----------------------------------------------------------------------------------

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.id' in 'where clause' (Connection: mysql, SQL: select count(*) as aggregate from `users` where (`users`.`id` = 8))
```

**Comment by yalsicor** [comment]
Just a hunch: in your search query parameter you are explicitly asking for the `id` column, could that be the culprit?
Also, is it even possible to search for a hashed key in the database? what layer would decode it before it is used in the query?

**Comment by Mohammad-Alavi** [comment]
In the `UserFactory`, you are setting `id` to `person_id`. 

`person_id' => Person::factory()->create()->id`

Shouldn't it be this? 

`person_id' => Person::factory()->create()->person_id`
